version: "3.9"

services:

  db:
    image: postgres:15
    container_name: moderator_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moderator_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend-moderation-platform
    container_name: moderator_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./backend-moderation-platform/.env

  frontend:
    build: ./frontend-moderation-platform
    container_name: moderator_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: